language: node_js
node_js:
- '0.11'
before_install: npm install -g gulp
script: NODE_ENV=PROD gulp
deploy:
  provider: s3
  access_key_id: AKIAI2O5LRFJZNIRLVBA
  secret_access_key:
    secure: IjUFRQYTsBsxrqTFWrTdg4n9WQ5IybCbOxs1b5piqfWRYwxFvJiUT4KEzYMrDCj84QKPdpZ81M+zPNulzR8yC4lzL+Nz5k8yKG/o50gH8whdEmClXDKInuzngoUcbauJzpzBlx56kf9MUiERCjIQa2dw31gRWcIg37GhcKBzXlM=
  bucket: hashtagcharity.org
  skip_cleanup: true
  region: us-west-2
  local-dir: dist
cache:
  directories:
    - node_modules
notifications:
  slack: hashtagcharity:iJNujPeyxMGap6QCsXZTaH64
